### ISSUE TITLE
Cannot load talents on pharo 6.1&7

### ISSUE THREAD

**Issue by mattonem** [pharo-contributions/pharo-talents#3]
I was expecting to have a lot fun playing around with talents but apparently it is not compatible with pharo6.1, is it ? 
I get the error: 'Name not found: shift-installer'. 
Are ficus depedencies wrong ? 
Do i need to upgrade to latest pharo 7  or is there a issue with the baseline ?

**Comment by mattonem** [comment]
great.
But I still cannot load it as part of another baseline.
I get:
Could not resolve: BaselineOfShift [BaselineOfShift] in D:\Pharo6.1\pharo-local\package-cache D:\Pharo6.1\pharo-local\iceberg\tesonep\shift\src (Libgit).

Is Tonel format supported by pharo 6.1 ?

**Comment by mattonem** [comment]
https://travis-ci.org/mattonem/pharo-talents/jobs/314817984
It also occurs on pharo 7...

**Comment by mattonem** [comment]
well actually it is because of smalltalkCI... it doesnt yet support tonel...
hpi-swa/smalltalkCI#326
My bad.

**Comment by seandenigris** [comment]
SmalltalkCI now supports Tonel and Pharo is at version 11. Perhaps we can close this issue?
